---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: thoughts-backend-ingress
    namespace: example
spec:
    rules:
        - host: thoughts.example.local
          http:
            paths:
              - backend:
                  service:
                    name: thoughts-service
                    port:
                      number: 80
                path: /
                pathType: Prefix
